### ISSUE TITLE
Error: Could not load the "sharp" module

### ISSUE THREAD

**Issue by faveoled** [Sandakan/Nora#226]
Ubuntu 22.04.3
```
$ ./Nora-Setup-2.5.0-stable-linux-x86_64.AppImage 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not load the "sharp" module using the linux-x64 runtime
ERR_DLOPEN_FAILED: libvips-cpp.so.42: cannot open shared object file: No such file or directory
Possible solutions:
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
  or
    npm install --force @img/sharp-linux-x64
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/tmp/.mount_Nora-SyTq9JM/resources/app.asar/node_modules/sharp/lib/sharp.js:85:9)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/tmp/.mount_Nora-SyTq9JM/resources/app.asar/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
```

**Comment by Sandakan** [comment]
can you try this solution from a previous issue #207. 

> `sudo apt install libvips` (or to be specific `libvips42`).
> And after that, both .deb installed pkg as well as the AppImage worked fine!

**Comment by faveoled** [comment]
Thanks, now it works
