### ISSUE TITLE
[Bug] AppImage package doesn't start

### ISSUE THREAD

**Issue by vitrola06** [Sandakan/Nora#245]
**OS**: Fedora 40 KDE on Wayland session
**Version**: v3.0.0-stable
Launching the program doesn't work, even with --no-sandbox argument. The process seems to start, but stops suddenly.
How can I troubleshoot this?
```A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not load the "sharp" module using the linux-x64 runtime
ERR_DLOPEN_FAILED: libvips-cpp.so.42: cannot open shared object file: No such file or directory
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/tmp/.mount_Nora.SUE8ocl/resources/app.asar/node_modules/sharp/lib/sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1391:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1451:10)
    at Module.load (node:internal/modules/cjs/loader:1214:32)
    at Module._load (node:internal/modules/cjs/loader:1030:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/tmp/.mount_Nora.SUE8ocl/resources/app.asar/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1391:14)

**Comment by Sandakan** [comment]
@vitrola06,
You can try the solution from #207.

> Did `sudo apt install libvips` (or to be specific libvips42).
> And after that, both .deb installed pkg as well as the AppImage worked fine!

**Comment by vitrola06** [comment]
My bad, didn't remember to check closed issues, only open ones. However, I have noticed this package is not available on Fedora or copr, so the only option would we be to build it from source, right? If this is the case, would it be better to just build Nora from source, which seems to work fine?

**Comment by IkelAtomig** [comment]
But libvips packages doesn't seem to found in dnf.

**Comment by IkelAtomig** [comment]
Just found that, it is just `vips` in dnf while as `libvips` in apt.

**Comment by vitrola06** [comment]
I think it would be nice for this info to be added to the README file. Other than that, thanks for the responses.
